version: '3.1'
services:
  proxy:
    image: nginx
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure
    volumes:
      - ./sites:/sites:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/usr/share/certs:ro
      #- "/root/auth/htpasswd:/etc/nginx/.htpasswd:ro"
    ports:
      - "8080:8080"
      #- "443:443"

  registry:
    image: registry
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure
    volumes:
      - "reg-data:/var/lib/registry:rw"
  
volumes: 
  reg-data: